- name: Port 3000 delete line to puma.rb 
  lineinfile:
    path: "/home/ec2-user/raisetech-live8-sample-app/config/puma.rb"
    state: present
    line: '# port ENV.fetch("PORT") { 3000 }'
    regexp: '^\s*port ENV\.fetch\("PORT"\) \{ 3000 \}$'
    insertafter: "^\\s*#\\s*Specifies the `port` that Puma will listen on to receive requests; default is 3000.\\s*#\\s*$"
    
- name: Puma service sample copy file to systemd puma service
  copy:
    remote_src: true
    src: "/home/ec2-user/raisetech-live8-sample-app/samples/puma.service.sample"
    dest: "/etc/systemd/system/puma.service"
  become: True
  become_user: root 

- name: Reload systemd daemon-reload
  systemd:
    daemon_reload: yes
  become: yes
  become_user: root

- name: sockets directory created to connect domain socket and start puma service
  file:
    path: "/home/ec2-user/raisetech-live8-sample-app/tmp/sockets"
    state: directory
    owner: "ec2-user"
    group: "ec2-user"
    mode: "775"

- name: pids directory created to connect domain socket and start puma service
  file:
    path: "/home/ec2-user/raisetech-live8-sample-app/tmp/pids"
    state: directory
    owner: "ec2-user"
    group: "ec2-user"
    mode: "775"

- name: Set up assets precompile on development rails app
  shell: bash -lc "RAILS_ENV=development bin/rails assets:precompile"
  args:
    chdir: /home/ec2-user/raisetech-live8-sample-app

- name: Start puma service
  service:
    name: puma
    state: started
  become: True
  become_user: root

- name: Enable puma service
  service:
    name: puma
    enabled: yes
  become: True
  become_user: root 
