version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.12.0
    steps:
      - checkout
      - run: python --version
      - add_ssh_keys:
          fingerprints:
            - "${KEY_FINGERPRINT}"

workflows:
  Deproy Rails Application using CFn and Ansible and CircleCI after Testing Serverspec:
    jobs:
      - build
