version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.13.1
    steps:
      - checkout
      - run: python --version
      - add_ssh_keys:
          fingerprints:
            - "SHA256:ZuGZ8jcJEaNL/Kf4MK+YSGGHNAenBJYyV/pMBOWbRJo"

workflows:
  Deproy Rails Application using CFn and Ansible and CircleCI after Testing Serverspec:
    jobs:
      - build
