version: 2.1
orbs:
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@3.1.1
jobs:
  cfn-lint:
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3002 -t task12-test/*.yml

  execute_cfn:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: create_stack_network
          command: |
            aws cloudformation deploy --stack-name lecture13-sample1 --template-file task12-test/task12-1.yml

workflows:
  raisetech:
    jobs:
      - cfn-lint
      - execute_cfn:
          requires:
            - cfn-lint
