- name: Comment out store uploaded files on the local file configration
  lineinfile:
    path: "/home/ec2-user/raisetech-live8-sample-app/config/environments/development.rb"
    state: present
    line: "  # config.active_storage.service = :local"
    regexp: "  config.active_storage.service = :local"  
    insertbefore:  "^\\s*#//s*Don't care if the mailer can't send.*$"

- name: Check if the comment line already exists
  shell: |
    grep -q "# Store uploaded files on the Amazon s3 service" /home/ec2-user/raisetech-live8-sample-app/config/environments/development.rb
  register: check_comment
  ignore_errors: true

- name: Comment in store uploaded files on the Amazon s3 service message and configration
  lineinfile:
    path: "/home/ec2-user/raisetech-live8-sample-app/config/environments/development.rb"
    state: present
    line: |
       # Store uploaded files on the Amazon s3 service (see config/storage.yml for options).
       config.active_storage.service = :amazon
    insertafter: "^\\s*# config.active_storage.service = :local*$"
  when: check_comment.rc != 0

- name: Read external variable file
  include_vars: "/home/circleci/project/Ansible/vars.yml"

- name: Config my S3 bucket name
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: "export AWS_S3_BUCKET_NAME={{  s3_bucket_name }}"
    state: present

- name: Source bash profile
  shell: bash -lc  "source /home/ec2-user/.bash_profile"
  become: true

- name: Restart puma service
  service:
    name: puma
    state: restarted
  become: True
  become_user: root    
