- name: Copy database.yml.sample to database.yml on Rails application
  copy: 
   remote_src: true
   src: "/home/ec2-user/raisetech-live8-sample-app/config/database.yml.sample"
   dest: "/home/ec2-user/raisetech-live8-sample-app/config/database.yml"

- name: Delete password default on my database.yml line
  lineinfile:
    path: "/home/ec2-user/raisetech-live8-sample-app/config/database.yml"
    state: absent
    regexp: "  password:"
    insertafter: "^\\s username: root*:*$"

- name: Change username on my database.yml line 
  lineinfile:
    path: "/home/ec2-user/raisetech-live8-sample-app/config/database.yml"
    state: present
    line: "  username: admin"
    regexp: "  username: root"
    insertafter: "^\\s*pool:*$"

- name: Change host on my database.yml line
  lineinfile:
    path: "/home/ec2-user/raisetech-live8-sample-app/config/database.yml"
    state: present
    line: "  host: rails-app-project-rds.cdisayw68dw6.ap-northeast-1.rds.amazonaws.com"
      #regexp: "    password:"  
    insertafter: "^\\s*username: admin*$"

- name: Change password on my database.yml line
  lineinfile:
    path: "/home/ec2-user/raisetech-live8-sample-app/config/database.yml"
    state: present
    line: "  password: pJhOqcfLh:|cHe[0{+e5u#4%<8Sm"
    insertafter: "^\\s*host:\\s.*\\.ap-northeast-1\\.rds\\.amazonaws\\.com$"
