# roles/db_server_role/tasks/main.yml
# lineinfile moduleでdbの認証情報を入力していますが,template moduleでも可能　使用したい方は下のコメントアウト値を参照

# circleciの絶対パスを指定CI/CDツールの環境に応じて変更
- name: Read external variable file
  include_vars: "/home/circleci/project/Ansible/vars.yml"

- name: Copy database.yml.sample to database.yml on Rails application
  copy: 
   remote_src: true
   src: "/home/ec2-user/raisetech-live8-sample-app/config/database.yml.sample"
   dest: "/home/ec2-user/raisetech-live8-sample-app/config/database.yml"

- name: Delete password default on my database.yml line
  lineinfile:
    path: "/home/ec2-user/raisetech-live8-sample-app/config/database.yml"
    state: absent
    regexp: "  password:"
    insertafter: "^\\s username: root*:*$"

- name: Change username on my database.yml line
  lineinfile:
    path: "/home/ec2-user/raisetech-live8-sample-app/config/database.yml"
    state: present
    line: "  username: {{ rds_master_user }}"
    regexp: "  username: root"
    insertafter: "^\\s*pool:*$"

- name: Change host on my database.yml line
  lineinfile:
    path: "/home/ec2-user/raisetech-live8-sample-app/config/database.yml"
    state: present
    line: "  host: {{ rds_end_point }}"
    insertafter: "^\\s*username: admin*$"

- name: Change password on my database.yml line
  lineinfile:
    path: "/home/ec2-user/raisetech-live8-sample-app/config/database.yml"
    state: present
    line: "  password: {{ rds_password }}"
    insertafter: "^\\s*host:\\s.*\\.ap-northeast-1.rds.amazonaws.com*$"
      
- name: Comment out "socket /tmp/mysql.sock" on my development environment
  lineinfile:
    path: "/home/ec2-user/raisetech-live8-sample-app/config/database.yml"
    state: present
    line: "# socket: /tmp/mysql.sock"
    regexp: "^\\s*socket: /tmp/mysql.sock$"
    insertafter: "^\\s*database: raisetech_live8_sample_app_development*$"

- name: Comment out "socket /tmp/mysql.sock" on my test environment
  lineinfile:
    path: "/home/ec2-user/raisetech-live8-sample-app/config/database.yml"
    state: present
    line: "# socket: /tmp/mysql.sock"
    regexp: "^\\s*socket: /tmp/mysql.sock$"
    insertafter: "^\\s*database: raisetech_live8_sample_app_test*$"      
