AWSTemplateFormatVersion: "2010-09-09"
Description: "Create an Load balancer for cloudformation"
Parameters:
  NameBase:
    Type: String
    Description: "Rails-app-Project-ALB"
    Default: "Rails-app-Project"

  ALBName:
    Type: String
    Default: "Rails-Project"

  IpAddressType:
    Type: String
    Default: "ipv4"

Resources:
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "${ALBName}-tg"
      Tags:
        - Key: Name
          Value: !Ref NameBase

      Port: 80
      Protocol: HTTP
      Matcher:
        HttpCode: '200'
      VpcId: !ImportValue "Rails-app-project-VPCid"
      TargetType: instance
      Targets:
        - Id: !ImportValue "Rails-app-Project-EC2"

  #=================================
  # ALBの作成
  #=================================
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: "application"
      Scheme: "internet-facing"
      Name: !Sub "${ALBName}-alb"
      IpAddressType: !Ref IpAddressType
      Subnets:
        - !ImportValue "Rails-app-project-PublicSubnet1id"
        - !ImportValue "Rails-app-project-PublicSubnet2id"
      SecurityGroups:
        - !ImportValue "Rails-app-Project-SG3-ALB"
      Tags:
        - Key: Name
          Value: !Ref NameBase

  #=================================
  # ALBをターゲットグループに関連付け
  #================================= 
  ListenerHTTP:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP

Outputs:
  OutputDNSName:
    Value: !GetAtt ALB.DNSName
    Export:
      Name: !Sub "${NameBase}-${ALBName}-dns-name"
  OutputHostZone:
    Value: !GetAtt ALB.CanonicalHostedZoneID
    Export:
      Name: !Sub "${NameBase}-${ALBName}-hostzoneid"
