AWSTemplateFormatVersion: 2010-09-09
Description: "Create an S3 bucket for cloudformation"

Parameters:

  NameBase:
    Type: String
    Description: "Rails-app-Project-S3"
    Default: Rails-app-Project

  S3BucketName: 
    Description: Type of this BucketName
    Type: String
    Default: "s3-bucket-name" 

  #-----------------------------------------------------------------------------
  # S3 bucket
  #-----------------------------------------------------------------------------
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${S3BucketName}
      LifecycleConfiguration:
        Rules:
          - Id: IntelligentTierRule
            Status: Enabled
            Transitions:
              - TransitionInDays: 0
                StorageClass: INTELLIGENT_TIERING
      IntelligentTieringConfigurations:
        - Id: DeepArchiveConfig
          Status: Enabled
          Tierings:
            - AccessTier: ARCHIVE_ACCESS
              Days: 180
            - AccessTier: DEEP_ARCHIVE_ACCESS
              Days: 365
      Tags:
        - Key: Name
          Value: !Ref NameBase

Outputs:
  S3BucketName:
    Value: !Ref S3Bucket
    Export:
      Name: Rails-app-Project-S3
