#- name: Port 3000 delete line to puma.rb 
#  lineinfile:
#    path: "/home/ec2-user/raisetech-live8-sample-app/config/puma.rb"
#    state: absent
#    line: '# port ENV.fetch("PORT") { 3000 }'
#    regexp: 'port ENV.fetch("PORT") { 3000 }'
#    insertbefore: "^# Specifies the `environment` that Puma will run in.$"
    
- name: Puma service sample copy file to systemd puma service
  copy:
    remote_src: true
    src: "/home/ec2-user/raisetech-live8-sample-app/samples/puma.service.sample"
    dest: "/etc/systemd/system/puma.service"
  become: True
  become_user: root 

- name: Reload systemd daemon-reload
  systemd:
    daemon_reload: yes
  become: yes
  become_user: root

    #- name: Start systemd Puma service
    # systemd: 
    #   name: puma
    #   state: started
    #  enabled: yes
    #  become: yes
    # become_user: root      

- name: Start puma service
  service:
    name: puma
    state: restarted
  become: True
  become_user: root

- name: Enable puma service
  service:
    name: puma
    enabled: yes
  become: True
  become_user: root
    
          #- name: Start puma service
          #  service:
          #    name: puma
          #    state: started
          #  become: True
          #  become_user: root

          #- name: Enable puma service
          #  service:
          #    name: puma
          #    enabled: yes
          #  become: True
          #  become_user: root 
