# roles/template_db_server_role/templates/nginx.conf

- name: Read external variable file
  include_vars: "/home/circleci/project/Ansible/vars.yml"

- name: Copy database.yml.sample to database.yml on Rails application
  copy: 
   remote_src: true
   src: "/home/ec2-user/raisetech-live8-sample-app/config/database.yml.sample"
   dest: "/home/ec2-user/raisetech-live8-sample-app/config/database.yml"

- name: Config database.yml for connecting Nginx server to Puma server 
  copy: 
    src: "/home/circleci/project/Ansible/roles/template_db_server_role/templates/database.yml"
    dest: "/home/ec2-user/raisetech-live8-sample-app/config/database.yml"
    remote_src: false  
    follow: yes

