# roles/template_db_server_role/templates/database.yml

- name: Read external variable file
  include_vars: "/home/circleci/project/Ansible/vars.yml"

- name: Config database.yml
  template: 
    src: "/home/circleci/project/Ansible/roles/template_db_server_role/templates/database.yml"
    dest: "/home/ec2-user/raisetech-live8-sample-app/config/database.yml"
    remote_src: false  
    follow: yes

