AWSTemplateFormatVersion: "2010-09-09"
Description: lecture10-cloudformation

Parameters:
  NameBase: 
    Description: this is base name.
    Type: String
    Default: lecture10-CFn

  # VPC
  VpcCIDR:
    Type: String
    Default: '10.0.0.0/16'

  # PublicSubnet
  PubSubCIDR1:
    Type: String
    Default: '10.0.0.0/20'

  PubSubAZ1:
    Type: String
    Default: 'ap-northeast-1a'

  PubSubCIDR2:
    Type: String
    Default: '10.0.16.0/20'
  
  PubSubAZ2:
    Type: String
    Default: 'ap-northeast-1c'

  # PrivateSubnet
  PriSubCIDR1:
    Type: String
    Default: '10.0.128.0/20'
  
  PriSubAZ1:
    Type: String
    Default: 'ap-northeast-1a'

  PriSubCIDR2:
    Type: String
    Default: '10.0.144.0/20'
  
  PriSubAZ2:
    Type: String
    Default: 'ap-northeast-1c'