AWSTemplateFormatVersion: 2010-09-09
Description: Create an S3 bucket

Parameters:
  OrganizationName:
    Description: Organization Name
    Type: String
  
  SystemName:
    Description: System Name
    Type: String

Resources:
  #-----------------------------------------------------------------------------
  # S3 bucket
  #-----------------------------------------------------------------------------
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${OrganizationName}-${SystemName}-bucket"
      
      Tags:
        - Key: Name
          Value: !Sub "${OrganizationName}-${SystemName}-bucket"
