AWSTemplateFormatVersion: "2010-09-09"
Description: lecture10-cloudformation

Parameters:

  SGName1:
    Type: String
    Default: 'lecture10-sg01'

Resources:
  lecture10SG1:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: create-ec2-sg
      GroupName: !Ref SGName1
      VpcId: !ImportValue lecture10-CFn-VPCid
      Tags:
        - Key: "Name"
          Value: "lecture10"