AWSTemplateFormatVersion: "2010-09-09"
Description: Create an EC2 instance with a key pair

Resources:
#-----------------------------------------------------------------------------
# IAM Role to access S3 Bucket
#-----------------------------------------------------------------------------
  S3AccessRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
  