AWSTemplateFormatVersion: "2010-09-09"
Description: Create an EC2 instance for circleci 

Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
  
  ProjectName:
    Type: String
    Description: Lecture10-CFn-EC2
    Default: "create-ec2"

  EC2InstanceVolumeSize:
    Type: String
    Default: "20"
  
  EC2InstanceVolumeType:
    Type: String
    Default: "gp2"
  
  EC2InstanceAMI:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"
    Description: The AMI ID for the EC2 instance


#-----------------------------------------------------------------------------
# IAM Role to access S3 Bucket and Session Manager
#-----------------------------------------------------------------------------
Resources:  
  AccessRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
  
  S3AccessPolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: s3access
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
              - s3:GetObject
              - s3:PutObject
              - s3:ListBucket
              - s3:DeleteObject
              - s3:GetBucketLocation
          Resource: "arn:aws:s3:::*"
        - Effect: Allow
          Action: "*"
          Resource:
            - "arn:aws:s3:::<lecture10-CFn-bucket>"
            - "arn:aws:s3:::<lecture10-CFn-bucket>/*"
      Roles:
      - !Ref AccessRole

  SSMAccessPolicies:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: "AmazonSSMManagedInstanceCore"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
              - "ssm:DescribeAssociation"
              - "ssm:GetDeployablePatchSnapshotForInstance"
              - "ssm:GetDocument"
              - "ssm:DescribeDocument"
              - "ssm:GetManifest"
              - "ssm:GetParameter"
              - "ssm:GetParameters"
              - "ssm:ListAssociations"
              - "ssm:ListInstanceAssociations"
              - "ssm:PutInventory"
              - "ssm:PutComplianceItems"
              - "ssm:PutConfigurePackageResult"
              - "ssm:UpdateAssociationStatus"
              - "ssm:UpdateInstanceAssociationStatus"
              - "ssm:UpdateInstanceInformation"
          Resource: "*"
        - Effect: Allow
          Action:
              - "ssmmessages:CreateControlChannel"
              - "ssmmessages:CreateDataChannel"
              - "ssmmessages:OpenControlChannel"
              - "ssmmessages:OpenDataChannel"
          Resource: "*"
        - Effect: Allow
          Action:
              - "ec2messages:AcknowledgeMessage"
              - "ec2messages:DeleteMessage"
              - "ec2messages:FailMessage"
              - "ec2messages:GetEndpoint"
              - "ec2messages:GetMessages"
              - "ec2messages:SendReply"
          Resource: "*"   
      Roles:
      - !Ref AccessRole
  
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - !Ref AccessRole 

  # ------------------------------------------------------------
  #  EC2の作成
  # ------------------------------------------------------------   
  Lecture10EC2CFn:
    Type: AWS::EC2::Instance
    Properties:
      BlockDeviceMappings:
        - DeviceName: /dev/sdb
          Ebs:
            VolumeSize: !Ref EC2InstanceVolumeSize
            VolumeType: !Ref EC2InstanceVolumeType
      IamInstanceProfile: !Ref InstanceProfile
      InstanceType: !Ref InstanceTypeParameter
      ImageId: !Ref EC2InstanceAMI
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          SubnetId: !ImportValue lecture10-CFn-PublicSubnet1id
          GroupSet:
            - !ImportValue "lecture10-sg-SG1-EC2"
      Tags:
        - Key: Name
          Value: !Ref ProjectName
      
  # ------------------------------------------------------------
  #  ElasticIPの作成&EC2にアタッチ
  # ------------------------------------------------------------ 
  ElasticIP:
    Type: "AWS::EC2::EIP"
    Properties:
      Domain: vpc

  IPAssoc:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref Lecture10EC2CFn
      EIP: !Ref ElasticIP

Outputs:
  InstanceId:
    Description: The Instance ID
    Value: !Ref Lecture10EC2CFn
    Export:
      Name: Lecture10-EC2CFn

  InstancePublicIp:
    Description: The public IP address of the EC2 instance
    Value: !GetAtt Lecture10EC2CFn.PublicIp
