AWSTemplateFormatVersion: "2010-09-09"
Description: Create an EC2 instance with a key pair

#-----------------------------------------------------------------------------
# IAM Role to access S3 Bucket
#-----------------------------------------------------------------------------
Resources: 
  S3AccessRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "IAMRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"

  AccessPolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: s3access
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: "Allow"
          Action:
              - s3:GetObject
              - s3:PutObject
              - s3:ListBucket
              - s3:DeleteObject
              - s3:GetBucketLocation
          Resource: "arn:aws:s3:::*"
        - Effect: Allow
          Action: "*"
          Resource:
            - "arn:aws:s3:::<lecture10-CFn-bucket>"
            - "arn:aws:s3:::<lecture10-CFn-bucket>/*"
      Roles:
      - !Ref S3AccessRole

