plugin: aws_ec2
regions: ap-northeast-1

# フィルタの設定
# "起動している"かつ"t2.micro"かつ"キーペア名test-keyを使用している" EC2インスタンスのみを対象
# tagの値が自身でで設定したタグ"'Rails-app-Project'のインスタンスのみを対象"
# cloudformationのスタック名のタグも指定する
filters: 
  instance-state-name: running
  instance-type: t2.micro
  # key-name:  ansible_test_key
  tag:Name: Rails-app-Project
  tag:aws:cloudformation:stack-name: EC2-Stack

# 取得したい値を設定(上から順)
hostnames:
  - ip-address

