- name: Clone Rails app source code
  git:  
    repo: https://github.com/yuta-ushijima/raisetech-live8-sample-app.git
    dest: /home/ec2-user/raisetech-live8-sample-app
  args:
  creates: /home/ec2-user/raisetech-live8-sample-app
