- name: Change username on my database.yml line 
  lineinfile:
    path: "/home/ec2-user/raisetech-live8-sample-app/config/environments/development.rb"
    state: present
    line: 'config.hosts << "anasible-test-1862325162.ap-northeast-1.elb.amazonaws.com"'
    insertafter: "^# Settings specified here will take precedence over those in config/application.rb.$"

- name: Retart puma service
  service:
    name: puma
    state: restarted
  become: True
  become_user: root      
