- name: Read external variable file
  include_vars: "/home/circleci/project/Ansible/vars.yml"

- name: Add line ALB dns config_hosts on my development environments
  lineinfile:
    path: "/home/ec2-user/raisetech-live8-sample-app/config/environments/development.rb"
    state: present
    line: 'config.hosts << "{{ alb_dnsname }}"'
    insertafter: "^\\s*#\\s*Settings specified here will take precedence over those in config/application.rb.*$"

- name: Retart puma service
  service:
    name: puma
    state: restarted
  become: True
  become_user: root      
